<?php

use Illuminate\Database\Seeder;

class InsuranceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('hospitals')->insert([
        [ 'name' => '臺北榮民總醫院', 'phone' => '02-2871-2121', 'address' => '112臺北市北投區石牌路二段201號'],
        [ 'name' => '臺北市立萬芳醫院', 'phone' => '02-2930-7930', 'address' => '116台北市文山區興隆路三段111號'],
        [ 'name' => '基督復臨安息日會醫療財團法人臺安醫院', 'phone' => '02-2771-8151', 'address' => '105台北市松山區八德路2段424號']
      ]);
      DB::table('claimables')->insert([
        [ 'name' => '住院前後門診', 'amount' => '250', 'max_count' => '2'],
        [ 'name' => '病房費用', 'amount' => '1000', 'max_count' => '30'],
        [ 'name' => '加護病房費用', 'amount' => '2000', 'max_count' => '10'],

        [ 'name' => '上消化道內視鏡息肉切除術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '上消化道泛內視鏡異物摘除術', 'amount' => '5000', 'max_count' => '1'],
        [ 'name' => '內視鏡喉頭異物取出術', 'amount' => '5000', 'max_count' => '1'],
        [ 'name' => '大腸鏡息肉切除術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '心導管合併氣球擴張術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '心導管合併支架置放術', 'amount' => '25000', 'max_count' => '1'],
        [ 'name' => '黃斑部雷射術', 'amount' => '5000', 'max_count' => '1'],
        [ 'name' => '趾甲部分摘除併母組織切除術', 'amount' => '1000', 'max_count' => '1'],
        [ 'name' => '經皮穿肝膽管引流術 P.T.C.D', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '肝腫瘤無線頻率電熱療法', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '骨髓移植術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '周邊造血細胞移植', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '三叉神經阻斷術', 'amount' => '1000', 'max_count' => '1'],
        [ 'name' => '氣管切開造口術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '椎間盤突出經皮導針Ｘ光導引燒灼術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '虹膜雷射術(青光眼)', 'amount' => '5000', 'max_count' => '1'],

        [ 'name' => '鼠蹊疝氣修補術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '眼瞼外翻矯正手術', 'amount' => '5000', 'max_count' => '1'],
        [ 'name' => '骨內固定物拔除術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '十字韌帶修補術', 'amount' => '12000', 'max_count' => '1'],
        [ 'name' => '體外震波碎石術', 'amount' => '5000', 'max_count' => '1'],
        [ 'name' => '輸尿管鏡取石術及碎石術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '胃全部切除術', 'amount' => '50000', 'max_count' => '1'],
        [ 'name' => '下顎骨脫位復位術', 'amount' => '5000', 'max_count' => '2'],
        [ 'name' => '肛門瘻切除或切開術併痔瘡切除', 'amount' => '10000', 'max_count' => '30'],
        [ 'name' => '懸壅顎咽成形術', 'amount' => '25000', 'max_count' => '10'],
        [ 'name' => '人工水晶體植入術', 'amount' => '12000', 'max_count' => '1'],
        [ 'name' => '膀胱攝護腺根除術', 'amount' => '40000', 'max_count' => '1'],
        [ 'name' => '腎臟移植', 'amount' => '60000', 'max_count' => '1'],
        [ 'name' => '全股關節置換術', 'amount' => '40000', 'max_count' => '1'],
        [ 'name' => '闌尾切除術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '顯微鏡下鼓膜切開術，併鼓室通氣管插入', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '粘膜下鼻甲切除術-單側/雙側', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '肌腱修補術', 'amount' => '6000', 'max_count' => '1'],
        [ 'name' => '椎間盤切除術 - 頸椎/腰椎', 'amount' => '30000', 'max_count' => '1'],
        [ 'name' => '腹腔鏡膽囊切除術', 'amount' => '30000', 'max_count' => '1'],
        [ 'name' => '腹腔鏡子宮肌瘤切除術', 'amount' => '10000', 'max_count' => '1'],
        [ 'name' => '腎鹿角石取石術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '冠狀動脈繞道手術', 'amount' => '90000', 'max_count' => '1'],
        [ 'name' => '肝臟移植', 'amount' => '100000', 'max_count' => '1'],
        [ 'name' => '主動脈瓣或二尖瓣或三尖瓣之置換手術', 'amount' => '20000', 'max_count' => '1'],
        [ 'name' => '開顱術摘除血管病變', 'amount' => '60000', 'max_count' => '1'],
        [ 'name' => '脊椎融合術', 'amount' => '40000', 'max_count' => '1'],
        [ 'name' => '全膝關節置換術', 'amount' => '35000', 'max_count' => '1'],
      ]);
      DB::table('insurance_policies')->insert([
        [ 'name' => '保單1基本', 'max_claimable_amount' => '100000'],
        [ 'name' => '保單2一般', 'max_claimable_amount' => '200000'],
        [ 'name' => '保單3高級', 'max_claimable_amount' => '300000']
      ]);
      DB::table('insurance_policies_claimables')->insert([
        [ 'claimable_id' => '1', 'insurance_policy_id' => '1'],
        [ 'claimable_id' => '2', 'insurance_policy_id' => '1'],
        [ 'claimable_id' => '3', 'insurance_policy_id' => '1'],
        [ 'claimable_id' => '1', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '2', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '3', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '4', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '5', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '6', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '7', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '8', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '9', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '10', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '11', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '12', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '13', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '14', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '15', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '16', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '17', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '18', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '19', 'insurance_policy_id' => '2'],
        [ 'claimable_id' => '1', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '2', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '3', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '4', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '5', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '6', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '7', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '8', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '9', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '10', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '11', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '12', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '13', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '14', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '15', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '16', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '17', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '18', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '19', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '20', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '21', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '22', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '23', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '24', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '25', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '26', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '27', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '28', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '29', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '30', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '31', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '32', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '33', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '34', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '35', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '36', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '37', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '38', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '39', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '40', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '41', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '42', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '43', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '44', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '45', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '46', 'insurance_policy_id' => '3'],
        [ 'claimable_id' => '47', 'insurance_policy_id' => '3'],
      ]);
      DB::table('users')->insert([
        [ 'username' => 'admin', 'password' => bcrypt('secret'), 'name' => '管理者', 'type' => 'Administrator'],
        [ 'username' => 'member1', 'password' => bcrypt('secret'), 'name' => '吳嘉豪', 'type' => 'Member'],
        [ 'username' => 'member2', 'password' => bcrypt('secret'), 'name' => '陳怡如', 'type' => 'Member'],
        [ 'username' => 'member3', 'password' => bcrypt('secret'), 'name' => '蔡歡怡', 'type' => 'Member'],
        [ 'username' => 'member4', 'password' => bcrypt('secret'), 'name' => '陳晴映', 'type' => 'Member'],
        [ 'username' => 'member5', 'password' => bcrypt('secret'), 'name' => '徐旻雯', 'type' => 'Member'],
        [ 'username' => 'member6', 'password' => bcrypt('secret'), 'name' => '羅淑婷', 'type' => 'Member'],
        [ 'username' => 'member7', 'password' => bcrypt('secret'), 'name' => '王旭枝', 'type' => 'Member'],
        [ 'username' => 'member8', 'password' => bcrypt('secret'), 'name' => '林文馨', 'type' => 'Member'],
        [ 'username' => 'member9', 'password' => bcrypt('secret'), 'name' => '楊育廷', 'type' => 'Member'],
      ]);
      DB::table('insurance_policies_users')->insert([
        [ 'user_id' => '2', 'insurance_policy_id' => '1' ],
        [ 'user_id' => '3', 'insurance_policy_id' => '2' ],
        [ 'user_id' => '4', 'insurance_policy_id' => '3' ],
        [ 'user_id' => '5', 'insurance_policy_id' => '1' ],
        [ 'user_id' => '6', 'insurance_policy_id' => '2' ],
      ]);
    }
}
